### PR TITLE
Fix: use outlet directly if route without element

### LINKED ISSUE #8492: [Bug]: Context prop in Outlet is not working with `index` routes.
### What version of React Router are you using?

6.1.1

### Steps to Reproduce

Setup project using below nested routes.
```
useRoutes([
    {
        path: '/',
        element: <Layout />,
        children: [
            {
                path: 'user',
                children: [
                    { index: true, element: <User /> },
                    { path: 'add', element: <AddUser /> },
                ],
            },
        ],
    },
])
```

and then use `<Outlet context={data} />` in `<Layout/>`

### Expected Behavior

Fetch `data` using `useOutletContext` hook.

### Actual Behavior

Getting `undefined` with `useOutletContext` hook.

### PR DESCRIPTION
**Pull request by liuhanqu**
Fix #8492

### CODE REVIEW

**Comment by timdorr** [comment]
Can you add a test to go with this?

**Comment by liuhanqu** [comment]
Ok, I will add test later.

**Review by timdorr — APPROVED** [review]
LGTM. Not sure if this needs MJ/RF's approval, but I went ahead and requested it anyways.

**Comment by michal-bednarz** [comment]
Hey @timdorr, any chances to get that PR merged? I have the same issue with the Outlet context & nested route without the `element` prop. Flattening structure helps, but I rather have my routes nested :)

**Review by JBaczuk — COMMENTED** [review]
Approved!

**Review by JBaczuk — APPROVED** [review]

**Comment by benfiglin** [comment]
Just found this, and this is the fix I need! Nested routes are quite useless to me without this. Would be great if you could merge it as soon as possible, thanks!

**Review by mjackson — APPROVED** [review]
Looks good, and thank you for the tests! We just need to fix up the PR title before merging.

**Comment by timdorr** [comment]
Looks like it's good now. Thanks!

**Pull request merged**
