### PR TITLE
docs：Add unstable_HistoryRouter to the api.md document

### PR DESCRIPTION
**Pull request by hsbtr**
A great idea

### CODE REVIEW

**Comment by hornta** [comment]
Why is this on hold? It's clearly a feature that needs to be documented even though it's marked as unstable.

**Comment by timdorr** [comment]
Some of the grammar was kind of awkward (I don't believe English is @hsbtr's first language). I reworded it for clarity now.

Thanks!

**Comment by hsbtr** [comment]
> Some of the grammar was kind of awkward (I don't believe English is @hsbtr's first language). I reworded it for clarity now.
> 
> Thanks!

Your guess is correct, English is indeed not my first language, thank you very much for pointing out and correcting my grammatical mistakes

**Comment by timdorr** [comment]
Thanks for getting things started in the first place!

**Comment by kris-slinger** [comment]
am facing this errors
export 'useHistory' (imported as 'useHistory') was not found in 'react-router-dom' 
export 'Redirect' (imported as 'Redirect') was not found in 'react-router-dom'

**Comment by hsbtr** [comment]
> am facing this errors export 'useHistory' (imported as 'useHistory') was not found in 'react-router-dom' export 'Redirect' (imported as 'Redirect') was not found in 'react-router-dom'

Two APIs have been removed in the V6 version, you can pay attention to useLoaction and Navigate

**Pull request merged**
