### PR TITLE
Support multiple usePrompt hooks in React tree

### PR DESCRIPTION
**Pull request by jaschaio**
See https://github.com/remix-run/react-router/discussions/9978

### CODE REVIEW

**Comment by cjsilva-umich** [comment]
Just curious as to why this was never merged in.

**Comment by Virthuss** [comment]
> Just curious as to why this was never merged in.

Agree. I need this as in my current situation I need multiple instances of blocker. Will this be merged anytime soon ? Thanks in advance !

**Comment by nivnahmias** [comment]
Can this pr please be addressed?

**Comment by nivnahmias** [comment]
@jaschaio can you please help out in explaining why this pr isn't addressed?

**Pull request closed without merging**
