### PR TITLE
feat: Re-export missing v6 features from react-router-dom-v5-compat package

### PR DESCRIPTION
**Pull request by zachgibb**
It seems like when these functions were created, they were not added to the list of exports in the compatibility package.

This PR re-exports the following from the `react-router-dom-v5-compat` package.

### Additions

**Types:**

- ActionFunction
- ActionFunctionArgs
- AwaitProps
- DataRouteMatch
- DataRouteObject
- Fetcher
- FormEncType
- FormMethod
- IndexRouteObject
- JsonFunction
- LoaderFunction
- LoaderFunctionArgs
- Navigation
- NonIndexRouteObject
- ParamKeyValuePair
- PathPattern
- RedirectFunction
- RelativeRoutingType
- RouterProviderProps
- ShouldRevalidateFunction
- SubmitOptions
- URLSearchParamsInit

**Classes**

- AbortedDeferredError

**Components**

- RouterProvider

**Routers**

- createBrowserRouter
- createHashRouter
- createMemoryRouter

**Hooks**

- useActionData
- useAsyncError
- useAsyncValue
- useLoaderData
- useMatches
- useNavigation
- useRevalidator
- useRouteError
- useRouteLoaderData

**Utilities**

- Await
- createRoutesFromElements
- defer
- isRouteErrorResponse
- json
- redirect

### CODE REVIEW

**Comment by zachgibb** [comment]
I could also re-export any of the other missing keys, as well, if that would be valuable?

**Comment by zachgibb** [comment]
Updated the PR to include all the missing exports from `react-router-dom`

**Comment by artaommahe** [comment]
@zachgibb btw `LinkProps` is still missed from the re-exports

**Comment by brophdawg11** [comment]
@zachgibb The v5 compat package is not intended to work with the new "data router" functionality introduced in 6.4.  the recommended upgrade path is to use the compat package to get to v6 `BrowserRouter`, then upgrade to `createBrowserRouter->RouterProvider`.

Are there any specific non-data-routing 6.3 things not being exported?

**Comment by zachgibb** [comment]
@brophdawg11 Ah, good to know. The project I was working on was restricted to working in a v5 host app, but we were trying to use some of the newer router features. It does seem that they work when re-exported, but I understand not wanting to continue to support that use case.

I went back to the 6.3 tag, and it does seem that the compat package is exporting all of the intended features for that version.

Should I just close this PR?

**Comment by MichaelDeBoey** [comment]
Closing this one as @zachgibb mentioned everything is working as expected

**Pull request closed without merging**
