### PR TITLE
Add generic type to `useLocation`

### LINKED ISSUE #8503: [Bug]: useLocation state unknow type in typescript
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

tsc --noEmit

### Expected Behavior

```
const { state } = useLocation();
console.log(state.userId); // ERROR: Object is of type 'unknown'
```

### Actual Behavior

useLocation must have a generic like this:

```
const { state } = useLocation<{ userId: number }>();
console.log(state.userId);
```

### PR DESCRIPTION
**Pull request by liuhanqu**
Fix #8503

### CODE REVIEW

**Comment by liuhanqu** [comment]
```typescript
const location = useLocation<value: string>();
console.log(location.state.value)  // value know as `string`
```

**Review by Amir-Alipour — APPROVED** [review]

**Comment by EliRobinson** [comment]
Are we able to get this deployed? This is a pretty big blocker for simple, quality typing in react router 6.

**Comment by mforman1** [comment]
Any update on this?

**Review by yhnavein — APPROVED** [review]

**Comment by indapublic** [comment]
@mjackson please

**Comment by ityuany** [comment]
same

**Comment by brophdawg11** [comment]
The [recommended solution](https://github.com/remix-run/react-router/issues/8503#issuecomment-998303553) of type narrowing is advised here, and also aligns with the `history` [release notes](https://github.com/remix-run/history/releases/tag/v5.2.0) documenting the `State` type change.

As [@larsenwork mentioned](https://github.com/remix-run/react-router/issues/8503#issuecomment-998780999) in #8503, this type of casting wouldn't provide any compile-time type safety.

**Pull request closed without merging**
