### PR TITLE
docs: add additional resources

### PR DESCRIPTION
**Pull request by rwieruch**
Not sure whether this is wanted, but I have written a quite extensive tutorial series about RR6. Perhaps there are people who read the docs who would be happy about some step by step instructions :) No hard feelings if that's not something you are looking for!

### CODE REVIEW

**Comment by timdorr** [comment]
Thanks, but I don't think that's the best place for those kinds of links. Most folks won't see that and it doesn't directly relate to the example code.

Instead, what might work better is a large docs page with links to various resources on the web, much like what we have on Redux: https://redux.js.org/introduction/learning-resources

**Comment by rwieruch** [comment]
Thanks @timdorr If you think a "Community Resources" page would be useful to people, I'd be happy to set it up. Just give me a hint where to start :)

**Comment by timdorr** [comment]
That would be in the docs folder: https://github.com/remix-run/react-router/tree/main/docs

Unfortunately, the website itself is maintained outside of this repo, so I'm not sure what is needed to get it into the sidebar menu.

**Comment by rwieruch** [comment]
@mjackson if a community resources page is something you may want to introduce for React Router, I could provide some content that may help people using it :) Everything written from scratch this year for RR6!

- [Introduction Tutorial](https://www.robinwieruch.de/react-router/)
- [Nested Routes](https://www.robinwieruch.de/react-router-nested-routes/)
- [Descendant Routes](https://www.robinwieruch.de/react-router-descendant-routes/)
- [Search Params](https://www.robinwieruch.de/react-router-search-params/)
- [Private Routes](https://www.robinwieruch.de/react-router-private-routes/)
- [Authentication with RR](https://www.robinwieruch.de/react-router-authentication/)

**Pull request closed without merging**
