### PR TITLE
README's fixes

### PR DESCRIPTION
**Pull request by refusado**
This pull request makes fixes to the README's examples. Some links to StackBlitz were not working due to differences in the name of some files. In addition, other StackBlitz links were also wrong. In both cases the user was redirected to the README inside the Stackblitz platform instead the App file.

### CODE REVIEW

**Comment by timdorr** [comment]
Can you remove the file renames from this PR? In those cases, the import statements are referencing `app.tsx`. For case-sensitive filesystems, this will cause the examples to not build.

**Comment by refusado** [comment]
@timdorr Indeed, this is an issue that I didn't take into account :man_facepalming:. Don't you think it would be better to update these imports to keep the standard in the file names?

**Comment by timdorr** [comment]
No point in changing something that isn't broken. Let's keep the PR simple and only update the README links.

**Comment by refusado** [comment]
@timdorr That makes sense. I removed the file name changes. Thank you

**Comment by timdorr** [comment]
Thanks!

**Pull request merged**
