### PR TITLE
Return the navigate promise

### PR DESCRIPTION
**Pull request by DanielSchiavini**
When navigate throws errors, it's impossible for the calling application to catch them. Navigate returns a promise and that promise should be returned to the caller.

### CODE REVIEW

**Comment by brophdawg11** [comment]
Thank you for the PR, but this is by design at the moment since it's cumbersome and error prone to deal with promises in React components.  Navigation errors should be handled by the [`errorElement`](https://reactrouter.com/en/main/route/error-element) when using a `RouterProvider`.

Eventually when the React `use` hooks lands as stable, this might be worth reconsidering, but until then I would say this should be opened as a `Proposal` Discussion so it can be considered for the roadmap via the [Open Development Process](https://remix.run/blog/open-development).

**Comment by DanielSchiavini** [comment]
@brophdawg11 thanks for reviewing the PR. I understand what you are saying, but I am puzzled with how to handle exceptions here. This specific function is throwing `AbortedError` when the navigation is interrupted by React Strict Mode.

**Comment by DanielSchiavini** [comment]
I understand that the better approach is to use the `action` for redirecting, but I have an existing app that I'm trying to migrate to Remix, and it would be appreciated if I can first migrate the app as is, and then refactor to use actions when appropriate.

I can try to provide a full reproduction scenario, but it's a complex application and that takes a lot of time :cry:

**Comment by brophdawg11** [comment]
That's totally understandable and I agree migrations are best done in this manner, but we can't change the API to expose an error-prone Promise into the render cycle just for this migration 😄 .  

Does the `AbortedError` cause issues in the UI?  Since it's a StrictMode dev-only thing, could you just catch the error and swallow it in dev mode?  It won't happen in production because your effects won't run twice.

**Comment by DanielSchiavini** [comment]
I don't think anybody can or should call navigate in the render cycle. This is only done with effects or callbacks I assume.
I'm trying to swallow the error globally without success yet.

**Pull request closed without merging**
