### PR TITLE
typo on installation.md

### PR DESCRIPTION
**Pull request by Ajayff4**
suggesting command correction for package installation.

### CODE REVIEW

**Comment by timdorr** [comment]
Anyone know why the CLA bot is failing here?

**Comment by mjackson** [comment]
@mcansh do you know why? Is it a casing thing? Or is it perhaps because @timdorr committed the change to the contributors.yml file instead of the OP?

**Comment by mcansh** [comment]
@mjackson yeah i'm pretty sure it's because @Ajayff4 want the one to add their name

**Comment by timdorr** [comment]
Do I need to sign as well, or just remove my commit?

**Comment by Ajayff4** [comment]
Do you need any help from me?

**Comment by timdorr** [comment]
Should be good to go now. Thanks!

**Pull request merged**
