### PR TITLE
fix: Update react dependencies to v18.1.0

### PR DESCRIPTION
**Pull request by benwis**
# Issue
react-router and react-router-dom's fixed react and react-dom dependencies are causing multiple versions of react and react-dom to be bundled in my remix app. 
# Fix
Update package.json to version 18.1. Alternatively this could be changed to be >16 like the other Remix packages I can confirm that this fixes it in my Remix stack.

### CODE REVIEW

**Comment by brophdawg11** [comment]
Thanks for the reproduction - the thing that's got me confused is why changing `@types/react` would have any impact on the actual `react` package used.  I'll pull down that repo and poke around a bit and see what I can find 👍

**Comment by benwis** [comment]
@brophdawg11  Oof, this is what I get when I submit PRs before coffee. I also needed to update the main react deps, and I have done so now

**Comment by brophdawg11** [comment]
haha, an all too common mistake!  

I'm trying to get your stack running locally on an M1 MBP but getting the following on rust installation step 2:

```bash
> curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
wasm-pack-init: no precompiled binaries available for CPU architecture: arm64
```

Any insights on building on an M1?  

I'm also curious if this double-dependency thing is deno-related - any idea if it's reproducible in a non-rust world using deno?

**Comment by benwis** [comment]
So far this is the only thing I have tried Deno with, but the build step doesn't use rust at all, so probably? I did not notice this error updating the blues stack to react 18 though.

I usually develop on an M1 Macbook Pro, you want to run `cargo install wasm-pack`, that should work fine on our computers but take a bit longer. I will update the instructions!

**Comment by brophdawg11** [comment]
ok - I got back around to playing with this locally today (thanks for the tip on `cargo install wasm-pack`)

On my very first install today I had a mismatch but that was with the version of this repo I cloned last week and it had a local `package-lock.json` so I had already done some stuff last week which could have borked the setup.

Today I tried cloning and installing fresh (without a `package-lock.json`) in the repo on both branches, and I wasn't able to reproduce the mismatch.

```bash
# A fresh install on main gave me properly deduped 17.0.2 packages
> git clone git@github.com:benwis/air-metal-stack.git
> cd air-metal-stack
> npm install
> npm ls react-dom
air-metal-stacl@0.0.1 ./air-metal-stack
└─┬ remix-air-metal@ -> ./packages/remix-app
  ├─┬ @remix-run/deno@1.5.1
  │ └─┬ @remix-run/server-runtime@1.5.1
  │   └── react-dom@17.0.2 deduped
  ├─┬ @remix-run/react@1.5.1
  │ ├── react-dom@17.0.2 deduped
  │ └─┬ react-router-dom@6.3.0
  │   └── react-dom@17.0.2 deduped
  └── react-dom@17.0.2

# Then I did a fresh install on the react-18 branch and got properly deduped versions there
> git checkout react-18
> rm -rf node_modules/
> rm -f package-lock.json
> npm install
> npm ls react-dom
remix-rust@0.0.1 /Users/matt/me/remix/repos/playgrounds/air-metal-stack2
└─┬ remix-air-metal@ -> ./packages/remix-app
  ├─┬ @remix-run/deno@1.5.1
  │ └─┬ @remix-run/server-runtime@1.5.1
  │   └── react-dom@18.1.0 deduped
  ├─┬ @remix-run/react@1.5.1
  │ ├── react-dom@18.1.0 deduped
  │ └─┬ react-router-dom@6.3.0
  │   └── react-dom@18.1.0 deduped
  └── react-dom@18.1.0
```

The dependencies you're updating in this PR are the monorepo deps for local development in `react-router` - but they aren't the deps for the published packages - those are all specified as `peerDependencies` which should support 17 or 18 without issue.

```
  "peerDependencies": {
    "react": ">=16.8",
    "react-dom": ">=16.8"
  },
```

I also tried creating a new app using `create-remix` using a template of your local repo on the `react-18` branch and that seemed ok too.  

Do you want to try this fresh and see if you're still hitting the issue?  See if you can find any specific steps that get you into this scenario?

**Comment by benwis** [comment]
Really appreciate the second pair of eyes on this. You are quite correct, once I deleted package-lock.json and reinstalled everything, all the React dependencies correctly parsed. God npm frustrates me sometimes. I am closing this, as it appears to not be an issue.

**Pull request closed without merging**
