### PR TITLE
Memoize result from useMatch() between renders

### LINKED ISSUE #7059: useRouterMatch returns new object on each render
## Version

5.1.2

## Test Case

https://codesandbox.io/s/eloquent-wave-vlixh

## Steps to reproduce

CodeSanbox has a reproducible case

## Expected Behavior

`useRouteMatch` hook returns a match object, when combined with a `useEffect` it is expected that the effect will run only when the window location or path parameters change

## Actual Behavior

`useRouteMatch` hook returns a match object, when combined with a `useEffect` with the match as dependency the effect is triggered on every state change.
The codesandbox example performs a state update on a timeout and logs `match` whenever it is changed. The logs show that on every update match has changed even if the path has not. Memoizing the `match` object on `window.location.pathname` prevents this and has the expected behaviour

[This line](https://github.com/ReactTraining/react-router/blob/e81dfa2d01937969ee3f9b1f33c9ddd319f9e091/packages/react-router/modules/hooks.js#L54) in the hook returns the result of [`matchPath`](https://github.com/ReactTraining/react-router/blob/e81dfa2d01937969ee3f9b1f33c9ddd319f9e091/packages/react-router/modules/matchPath.js#L55) which creates a new object every time it is executed.
Possible solution would be to do something like
```js
return path ? 
  useMemo(() => matchPath(location.pathname, path), [location.pathname, path]) :
  match
```

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #7059

### CODE REVIEW

**Comment by timdorr** [comment]
@jonkoops Can you fix the formatting? Just run Prettier on the code and it should be good to go.

**Comment by jonkoops** [comment]
@timdorr Done :+1:

**Comment by timdorr** [comment]
This needs to go into the `dev` branch. I updated the base on the PR, can you do the rebase? I can only make new commits on your fork, not force push.

**Comment by jonkoops** [comment]
@timdorr Rebased on `dev` :+1:

**Comment by timdorr** [comment]
Cool, let's get this in. Thanks!

**Pull request merged**
