### PR TITLE
fix(react-router): improve memoization for context providers

### PR DESCRIPTION
**Pull request by appden**
This will reduce some unnecessary re-renders where the context is accessed.

### CODE REVIEW

**Comment by brophdawg11** [comment]
@appden Thanks for this!  Do you happen to have an example of the `useBlocker` issue you're fixing with the latest commit?  I'm tempted to deal with that separately...

**Comment by appden** [comment]
> @appden Thanks for this! Do you happen to have an example of the `useBlocker` issue you're fixing with the latest commit? I'm tempted to deal with that separately...

No prob! I made that commit because I originally neglected to run tests (doh) and saw several tests in `use-blocker-test.tsx` fail on CI that I presume would have blocked merging this in.

**Comment by brophdawg11** [comment]
Ah ok if they were caused by these changes that makes sense.  I'll try to do some deeper testing on this next week 👍

**Comment by appden** [comment]
Hi @brophdawg11, kindly follow up to see if you've had the chance to test this further. Thanks!

**Review by brophdawg11 — APPROVED** [review]

**Comment by brophdawg11** [comment]
Thanks @appden!

**Pull request merged**
