### PR TITLE
Use react createContext instead

### PR DESCRIPTION
**Pull request by hamidreza-nateghi**

### CODE REVIEW

**Comment by timdorr** [comment]
The dependencies should also be updated to remove `mini-create-react-context`.

**Comment by hamidreza-nateghi** [comment]
> The dependencies should also be updated to remove `mini-create-react-context`.

How can I add more commits to this PR?

**Comment by timdorr** [comment]
Instructions are on the green Code button above:

image

**Comment by ethan-pearce** [comment]
> The dependencies should also be updated to remove `mini-create-react-context`.

I ran into an issue because it's not actually in the dependencies, so think this is good to go !

**Comment by pshrmn** [comment]
You need to check the `package.json` files for the individual packages

https://github.com/remix-run/react-router/blob/13ca8a58c5501c107e0d430464545f574a5f7010/packages/react-router/package.json#L43

**Pull request closed without merging**
