### PR TITLE
Use `Pick` instead of `Omit`

### PR DESCRIPTION
**Pull request by liuhanqu**
Pick the property that would be use in `navigator`, so we can know which method can be use explicitly.

### CODE REVIEW

**Comment by ryanflorence** [comment]
Can you make this against the `dev` branch please, thanks :)

**Comment by liuhanqu** [comment]
It's ok.

**Comment by timdorr** [comment]
BTW, to review the actual code change here, just look at this commit: 47a5c32

**Comment by timdorr** [comment]
I think Ryan was OK with this, so Imma merge this. Thanks @liuhanqu!

**Pull request merged**
