### PR TITLE
chore: add frontmatter to examples for website

### PR DESCRIPTION
**Pull request by mcansh**
closes [REM-471](https://linear.app/remix-run/issue/REM-471)

### CODE REVIEW

**Comment by timdorr** [comment]
Hey @mcansh, it looks like this knocked all the examples off the website. Should we revert or try to fix the website build?

**Comment by mcansh** [comment]
> Hey @mcansh, it looks like this knocked all the examples off the website. Should we revert or try to fix the website build?

cutting a build to bring them back now! had some website changes so examples are auto added to the website

**Comment by mcansh** [comment]
they're back! https://reactrouter.com/docs/en/v6/examples

**Comment by timdorr** [comment]
@mcansh I'm actually getting a 404 on all docs pages now :|

**Comment by mcansh** [comment]
@timdorr yeah.. we're not exactly sure what happened there... worked when I sent the message, then somewhere between that and 6.0.2 they all got deleted - keeping an eye on it :+1:

**Pull request merged**
