### PR TITLE
fix: respect basename in loaders and actions redirects

### PR DESCRIPTION
**Pull request by manzano78**
Closes https://github.com/remix-run/react-router/issues/9417

### CODE REVIEW

**Comment by brophdawg11** [comment]
Thanks for the PR @manzano78!  Do you want to try adding a unit test for this to the `router-test.ts` file?  If not I can get one added 😄

**Comment by manzano78** [comment]
> Thanks for the PR @manzano78! Do you want to try adding a unit test for this to the `router-test.ts` file? If not I can get one added 😄

In view of this test file, I think it'd probably be better (for my brain and for the conservation of your strict testing conventions)  if you add it 😄 I hope you don't mind!

**Comment by manzano78** [comment]
@brophdawg11 , FIY the bundles size test failed because `packages/router/dist/router.js` exceeded 100kb. As a "workaround" to go back under this threshold, I shortened my code explanation comment. I feel it could be a good solution to increase a little bit this threshold or maybe, if it's possible, to exclude comments from the bundle size calculation to avoid shortening comments as I did :)

**Comment by brophdawg11** [comment]
👍 Thanks @manzano78, I'll merge this into a branch of mine and get the tests added there

**Pull request merged**
