### PR TITLE
Support base64 encoded ids on nested routes

### LINKED ISSUE #8288: [Bug]: Nested routes under an id with a trailing `=` fail to match
### What version of React Router are you using?

6.0.0

### Steps to Reproduce

Create a nested route
```jsx
<Routes>
   <Route path="/dashboard/:dashboardId" element={<DashboardPage />}>
      <Route path="edit" element={<EditDasbhboard />}>
   </Route>
</Routes>
```

If the `:dahboardId` contains an equals sign at the end (e.x. a relay Id like `RGFzaGJvYXJkOjE2MzU=`), the generated regex `^\/dashboards\/([^\/]+)(?:\b|$)`  fails to capture the `=` at the end when the pathname is `/dashboards/RGFzaGJvYXJkOjE2MzU=/edit`

### Expected Behavior

The generated regex that matches the `:dashboardId` should capture all the way up to the next forward slash.

### Actual Behavior

`pathname.match` matches up to the `=` (`/dashboards/RGFzaGJvYXJkOjE2MzU`) but fails to capture the trailing `=`, causing the router to say that there are no matches for the nested route.

### PR DESCRIPTION
**Pull request by mikeldking**
Resolves #8288 

This PR modifies `compilePath`'s non-capturing group to match up to the proceeding `/` so that paths with base64 encoded ids  (e.x.`users/RGFzaGJvYXJkOjE1Nzk=/edit` when using `graphql-relay` globalIds) properly match up to the `/` and not at the word break before the `=` character.

### CODE REVIEW

**Comment by mjackson** [comment]
Thanks for the PR, @mikeldking! I'll review this today.

Just making a note for myself here: I think the word boundary check should come when we know we are replacing a `:id`-style URL param. So I'm going to try making that adjustment myself when this gets merged.

**Comment by mikeldking** [comment]
Thanks for taking a look @mjackson ! Looking forward to contributing.

Agreed on the boundary check - doesn't need to be there when the path is terminating in a `:id` style param. Went for the smallest change that satisfied the use case for not matching `/home2` for `/home`  but also matching `/users/:id/edit` for `/users/Axy=/edit`.

**Comment by iMoses-Apiiro** [comment]
seems like this would also solve #7987

**Comment by mikeldking** [comment]
Hey @mjackson @chaance super gentle nudge on this PR! Excited about the news w/ remix-run! I'm currently working around this bug by adding a `*` at the end of my routes to avoid the over-eager non-matching group. Very excited to be an early adopter of the new router and more than happy to make adjustments to this PR as needed! Thanks again for your work.

**Review by mjackson — APPROVED** [review]

**Comment by ryanflorence** [comment]
Thanks @mikeldking

**Pull request merged**
