### PR TITLE
Update on file use-location.md

### PR DESCRIPTION
**Pull request by KubasuIvanSakwa**
tried to add some more context on useLocation in the docs folder in file use-location.md

### CODE REVIEW

**Comment by brophdawg11** [comment]
It seems like the goal here is to elaborate on the different properties on a `location`?  If so I don't think we need this type of code example - but we _are_ missing the `Path` definition in the "Type declaration" section.  Could we update that section and then just add the list of properties like we do in the [Remix docs](https://remix.run/docs/en/main/hooks/use-location)?

**Comment by KubasuIvanSakwa** [comment]
I have seen the [Remix Docs](https://remix.run/docs/en/main/hooks/use-location#locationpathname) so the properties should be listed in that manner in the [React-Router docs](https://reactrouter.com/en/main/hooks/use-location)

**Comment by brophdawg11** [comment]
Do you want to make those updates in this PR?

**Comment by KubasuIvanSakwa** [comment]
yes I have already made the changes of type declaration in this pull request and deleted the previous changes that I had requested

**Review by brophdawg11 — APPROVED** [review]

**Comment by brophdawg11** [comment]
Thanks!

**Pull request merged**
