### PR TITLE
Fix: cant start route with @ within Layout Routes (#8699)

### PR DESCRIPTION
**Pull request by theostavrides**
Fixes bug #8699 

When a route is nested within a layout route, it wont render routes starting with an '@' symbol:
```
<Routes>
    <Route element={<Layout />}>
        <Route path=":id" element={<Chat />} />
    </Route>
</Routes>
```

Note that the router works correctly when the parent is NOT a layout route (i.e. has a path defined), or is at the root level:
```
    <Router>
      <Routes>
        <Route path=":id" element={'works with /@tom'}/>
        <Route path="nested">
          <Route path=":id" element={'works with /nested/@tom'}/>
        </Route>
      </Routes>
    </Router>
```

### CODE REVIEW

**Comment by knpwrs** [comment]
This would also fix https://github.com/remix-run/remix/issues/2012

**Comment by kgamecarter** [comment]
also fix https://github.com/remix-run/remix/issues/846

**Review by chaance — APPROVED** [review]

**Comment by chaance** [comment]
@theostavrides I'd love to merge this. Would you mind resolving the merge conflicts and updating your branch?

It's actually simple, we just reorganized our file structure a bit and the updated code is now in `react-router/lib/router.ts`. Thanks a ton!

**Comment by theostavrides** [comment]
@chaance Would be happy to.  I'll get on it tomorrow

**Pull request closed without merging**
