### PR TITLE
Allow NavLink to receive a children function

### PR DESCRIPTION
**Pull request by sergiodxa**
Right now the NavLink component has this useful className and style function support to change the styles if the link is active.

```jsx
<NavLink to="." className={({ isActive }) => isActive ? activeClassName : inactiveClassName}>Content</NavLink>
```

```jsx
<NavLink to="." style={({ isActive }) => isActive ? activeStyles : inactiveStyles}>Content</NavLink>
```

This is really cool, but one use case it doesn't support, but it's really easy to add support for, is what happens if inside the NavLink there are two, or more, elements and they need to change styles based on the isActive state, right now it's not really possible to detect that, specially when using utility CSS.

This PR adds support for that, which was also requested on the discussion #8080, copying the example from that discussion, now this is possible:

```jsx
<NavLink to="path">
  {({isActive}) => (
    <>
      <Icon className={isActive ? 'text-blue-500' : 'text-gray-500'} />
      <span className={isActive ? 'text-blue-900' : 'text-gray-700'}>Link</span>
    </>
  )}
</NavLink>
```

I also updated the `docs/api.md` to mention and show an example of this and the tests of the NavLink component to test this works.

### CODE REVIEW

**Comment by mcansh** [comment]
this is technically possible using a custom (Nav)Link component with the `useResolvedPath` and `useMatch` hooks - https://reactrouter.com/docs/en/v6/examples/custom-link. here's an example using an icon https://stackblitz.com/edit/github-kzress?file=src/App.tsx

**Review by mcansh — APPROVED** [review]

**Comment by ryanflorence** [comment]
Let's do it, @sergiodxa, I fixed the conflicts, you want to sign the contributors.yml in this PR and I'll merge it?

**Comment by sergiodxa** [comment]
> Let's do it, @sergiodxa, I fixed the conflicts, you want to sign the contributors.yml in this PR and I'll merge it?

Done! :shipit:

**Comment by timdorr** [comment]
Fixed up the formatting for you, but it looks like there are a couple of test failures, unfortunately.

**Comment by sergiodxa** [comment]
@timdorr I'm pretty sure it should be fixed now, could you run the workflow again? 🙏

**Pull request merged**
